### ISSUE TITLE
Sessions TODO

### ISSUE THREAD

**Issue by AFCMS** [AFCMS/minetest-skin-server#499]
- [ ] Optional Redis support
- [ ] Clear sessions for user
- [ ] Allow user to see all opened sessions
